name: katotakid
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  easy_localization: ^3.0.1
  flutter_bloc: ^8.0.1
  flutter_svg: ^0.23.0+1



flutter:

  uses-material-design: true

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/font/Gotham-LightItalic.ttf
          style: italic
        - asset: assets/font/Gotham-Medium.ttf
          style: normal

  assets:
    - assets/text/
    - assets/images/
    - assets/bubbles/
